### ISSUE TITLE
Error when appending timeseries data

### ISSUE THREAD

**Issue by zippiguy** [afiedler/tstables#6]
Code with results from Jupyter:

import tables
import tstables
from datetime import *
from pandas import pandas
from csv import reader

class tick(tables.IsDescription):
    timestamp = tables.Int64Col(pos=0)
    ask = tables.Float64Col(pos=1)
    bid = tables.Float64Col(pos=2)
    askvolume = tables.Float64Col(pos=3)
    bidvolume = tables.Float64Col(pos=4)

ticks = pandas.read_csv('EURUSD.csv',index_col=0,parse_dates=[0])

ticks.head()

---------------------------------------------------------------------------
	Ask 	Bid 	AskVolume 	BidVolume
DateTime 				
2017-01-01 22:00:20.786 	1.05236 	1.05148 	0.75 	0.75
2017-01-01 22:00:36.636 	1.05236 	1.05153 	0.75 	1.50
2017-01-01 22:01:37.024 	1.05236 	1.05153 	0.75 	1.50
2017-01-01 22:02:18.648 	1.05236 	1.05170 	0.75 	2.25
2017-01-01 22:02:30.583 	1.05248 	1.05170 	1.50 	2.25
---------------------------------------------------------------------------

f = tables.open_file('eurusd.h5','a')
ts = f.create_ts('/','EURUSD',tick)
ticks.index.__class__

---------------------------------------------------------------------------
pandas.core.indexes.datetimes.DatetimeIndex
---------------------------------------------------------------------------

ts.append(ticks)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-d851937966d0> in <module>()
----> 1 ts.append(ticks, convert_strings=False)

C:\ProgramData\Anaconda3\lib\site-packages\tstables\tstable.py in append(self, rows, convert_strings)
    237             if rows.empty:
    238                 return # Do nothing if we are appending nothing
--> 239             if rows.index.__class__ != pandas.tseries.index.DatetimeIndex:
    240                 raise ValueError('when rows is a DataFrame, the index must be a DatetimeIndex.')
    241 

AttributeError: module 'pandas.tseries' has no attribute 'index'
---------------------------------------------------------------------------

I am using:
Python 3.6.1
Pandas 20.2
PyTables 3.2.2
TsTables 0.0.15

Being fairly new to Python, I suspect that this may have something to do with recent changes in the way Pandas creates indexes.  But, I am having difficulty figuring out how to resolve this error.

Thanks,
Paul J.

**Comment by JiapengWang** [comment]
change "pandas.tseries.index.DatetimeIndex:" to "pandas.DatetimeIndex"

**Comment by zippiguy** [comment]
After much research, I finally found that pandas.tseries is deprecated several versions ago.  And, the above change in tstable.py does seem to work.  Much thanks!

At this point, I wonder if the developer would make this change and provide an updated release of TsTables.
